// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PikaModel;

namespace PikaModel.Migrations
{
    [DbContext(typeof(PikabuContext))]
    partial class PikabuContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PikaModel.Comment", b =>
                {
                    b.Property<long>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)");

                    b.Property<long?>("CommentContentId")
                        .HasColumnType("bigint(20)");

                    b.Property<DateTime>("DateTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint(20)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int(11)");

                    b.Property<int>("StoryId")
                        .HasColumnType("int(11)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(100)");

                    b.HasKey("CommentId")
                        .HasName("PRIMARY");

                    b.HasIndex("CommentContentId");

                    b.HasIndex("DateTimeUtc");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserName");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("PikaModel.CommentContent", b =>
                {
                    b.Property<long>("CommentContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)");

                    b.Property<string>("BodyHtml")
                        .HasColumnType("longtext");

                    b.HasKey("CommentContentId")
                        .HasName("PRIMARY");

                    b.ToTable("CommentContents");
                });

            modelBuilder.Entity("PikaModel.FetcherStat", b =>
                {
                    b.Property<string>("FetcherName")
                        .HasColumnType("varchar(255)");

                    b.Property<double>("StoriesPerSecondForLastHour")
                        .HasColumnType("double");

                    b.Property<double>("StoriesPerSecondForLastMinute")
                        .HasColumnType("double");

                    b.HasKey("FetcherName")
                        .HasName("PRIMARY");

                    b.ToTable("FetcherStats");
                });

            modelBuilder.Entity("PikaModel.Story", b =>
                {
                    b.Property<int>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Author")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastScanUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int(11)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("StoryId")
                        .HasName("PRIMARY");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("PikaModel.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("longtext");

                    b.HasKey("UserName")
                        .HasName("PRIMARY");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PikaModel.Comment", b =>
                {
                    b.HasOne("PikaModel.CommentContent", "CommentContent")
                        .WithMany("Comments")
                        .HasForeignKey("CommentContentId");

                    b.HasOne("PikaModel.Story", "Story")
                        .WithMany("Comments")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PikaModel.User", "UserNameNavigation")
                        .WithMany("Comments")
                        .HasForeignKey("UserName");
                });
#pragma warning restore 612, 618
        }
    }
}
